### ISSUE TITLE
Add a scheduler function, like a cron job -- so we can make this long running

### ISSUE THREAD

**Issue by buroa** [mza921/Plex-Auto-Collections#99] opened 2020-11-05 19:51 UTC
I'd like to deploy this into my Kubernetes cluster, so would love for this to be long-running and on a schedule, like per day run... per hour... etc.

**Comment by burkasaurusrex** [comment] 2020-11-09 07:14
Duplicate of #67

**Comment by sean-marks** [comment] 2020-12-21 15:23
Seems duplicate and could be closed?

**Closed** 2020-12-21 22:01 UTC
